language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"
install:
    - "pip install --upgrade pip"
    - "pip install stormpath-sdk --pre"
    - "pip install ."
script: python setup.py test

env:
    - DJANGO=1.6
    - DJANGO=1.7
