language: python
sudo: false
python:
- '2.7'
- '3.3'
- '3.4'
- pypy
install:
- pip install -e .[test]
- pip install -q Django==$DJANGO
before_script: python setup.py testdep
script:
- python setup.py test
after_success:
- coverage xml
- coveralls
- python-codacy-coverage -r coverage.xml
env:
  matrix:
  - DJANGO=1.6.11
  - DJANGO=1.7.7
  - DJANGO=1.8
  global:
  - secure: GFi89QUW5XQtuOMADHpExUsDblbG6XIHQ1DA5GY9Ij7Nkkg3dMqCwHU47oKHyrroDm/oInY2JwEpkYwLQfuiqASDZKXad2JA7CvsXrEiInc4GCKLCdas3/mLXRsprS7pTzr6VR9O22gwlk9TQ43RhNlrb8YF2eY9RUZM+Q9AucM=
  - secure: kl0oENGSTvXFMYvhWcBT/4b5WBZcgpel8Ky/RnCwy5Ym3j56g9MIsjS2+razPWMieByveLJOwrLbAA78zZIGoxqH61z9xo3oh+E+XMEOfsrmjaYFM/Y21ROtWkjJIWdNM7klrnryWtF4AYUXPZEsCpr6iNru4vB6CTr1s7FlsHg=
