language: python
sudo: false
python:
- '2.7'
- '3.4'
- '3.5'
- pypy
install:
- pip install -e .[test]
- pip install -q Django==$DJANGO
script:
- python setup.py test
after_success:
- cd testproject && coverage xml
- coveralls
- python-codacy-coverage -r coverage.xml
env:
  matrix:
  - DJANGO=1.7
  - DJANGO=1.8
  - DJANGO=1.9
  - DJANGO=1.10
  global:
  - GOOGLE_CLIENT_ID=xxx
  - GOOGLE_CLIENT_SECRET=xxx
  - FACEBOOK_CLIENT_ID=xxx
  - FACEBOOK_CLIENT_SECRET=xxx
  - GITHUB_CLIENT_ID=xxx
  - GITHUB_CLIENT_SECRET=xxx
  - LINKEDIN_CLIENT_ID=xxx
  - LINKEDIN_CLIENT_SECRET=xxx
  - secure: J24jJ8Sp6e0At5raohFTqx/g2gtBkdTHQ4kk1nvbe/aGrHJbwJNliXEwNftOLm39eyoUyzRx6qXliEGf7Pk7Xwt4xtfcaEq0hnzpdw3CREQOi0h8udY5UIOFGabGPyTjN5lNJTGGINcGl3pjqd1+JCDfnM/nqbTfPQ3wRhKOlbM=
  - secure: WKDRKgGrvuVSzArPkrihdmkQEC9F5NqS4Kf3nC5xFCFuM+HcnhhAXAYk/zaFv7vliy1bm2c6FMbTTtnH4r3qBS7QV0Cj3vPsrZxTGuFsME80/g5eRc30laBlyBV8JiFVPIX9GeoxUiMivuki+ja0MdEvUGP8ERgV1tQcNLEPSh0=
  - secure: ST9PPcRbrRtS/xeWamdabc+0Q7MpfGd9X0Ewq5MONvfzX1p9Z/6+dZRAmxUw9RJopjBWKSdfkC8rrkPbfFQw9++oRW9YCghHjlq8W7sJU7cN/Fn8BJgOJsxzoXdjOMVqI5Ta7PLHsradcW+VGeIj/5uFPA+amJwv/OW0gUDBrgg=
